site_name: jax-pdf
site_description: Probability density functions for MCMC/VI testing
repo_url: https://github.com/alekthiery/jax-pdf

theme:
  name: material
  palette:
    scheme: default

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            docstring_style: google

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Distributions: distributions.md
  - API Reference: api.md
